export const siteConfig = {
  name: "Renault Dacia Safi",
  fullName: "Renault Dacia Safi — Dacia Safi Auto Abda",
  tagline: {
    fr: "Votre concessionnaire Renault & Dacia à Safi",
    ar: "وكيل سيارات رينو وداسيا في آسفي",
  },
  description: {
    fr: "Renault Dacia Safi, votre concessionnaire de référence à Safi. Découvrez les nouveaux modèles 2026, véhicules d'occasion certifiés, financement, entretien et assurance automobile. Showroom Route de l'Avenue Hassan II.",
    ar: "رينو داسيا آسفي، وكيلكم المرجعي في آسفي. اكتشفوا الموديلات الجديدة 2026، سيارات مستعملة معتمدة، التمويل، الصيانة وتأمين السيارات. صالة العرض Route de l'Avenue Hassan II.",
  },
  category: "Concessionnaire automobile",
  phone: "+212 5 24 62 66 77",
  phoneRaw: "+212524626677",
  whatsapp: "212524626677",
  email: "contact@renaultdaciasafi.ma",
  address: {
    street: "Route de l'Avenue Hassan II",
    city: "Safi",
    region: "Marrakesh-Safi",
    country: "Maroc",
    countryCode: "MA",
    postalCode: "46000",
  },
  coordinates: {
    lat: 32.2994,
    lng: -9.2372,
  },
  hours: [
    { fr: "Lundi - Samedi", ar: "الإثنين - السبت", time: "08:30 - 19:00" },
    { fr: "Dimanche", ar: "الأحد", time: "09:00 - 13:00" },
  ],
  social: {
    facebook: "https://facebook.com/renaultdaciasafi",
    instagram: "https://instagram.com/renaultdaciasafi",
    twitter: "https://twitter.com/renaultdaciasafi",
    youtube: "https://youtube.com/@renaultdaciasafi",
  },
  stats: [
    { key: "models", value: "12", suffix: "+", icon: "car" },
    { key: "sold", value: "350", suffix: "/an", icon: "trending" },
    { key: "experience", value: "20", suffix: "ans", icon: "shield" },
    { key: "clients", value: "5000", suffix: "+", icon: "users" },
  ],
  brands: [
    { name: "Dacia", tagline: { fr: "Robuste & accessible", ar: "متين وفي المتناول" } },
    { name: "Renault", tagline: { fr: "Innovation & style", ar: "ابتكار وأناقة" } },
  ],
  vehicles: [
    {
      key: "sandero",
      brand: "Dacia",
      name: "Dacia Sandero",
      category: { fr: "Citadine", ar: "سيارة حضرية" },
      price: 119900,
      year: 2026,
      fuel: { fr: "Essence", ar: "بنزين" },
      transmission: { fr: "Manuelle", ar: "يدوي" },
      power: "90 ch",
      image:
        "/images/sandero.jpg",
      featured: true,
    },
    {
      key: "duster",
      brand: "Dacia",
      name: "Dacia Duster",
      category: { fr: "SUV", ar: "سيارة دفع رباعي" },
      price: 199900,
      year: 2026,
      fuel: { fr: "Diesel", ar: "ديزل" },
      transmission: { fr: "Manuelle", ar: "يدوي" },
      power: "115 ch",
      image:
        "/images/duster.jpg",
      featured: true,
    },
    {
      key: "jogger",
      brand: "Dacia",
      name: "Dacia Jogger",
      category: { fr: "Familiale 7 places", ar: "عائلية 7 مقاعد" },
      price: 179900,
      year: 2026,
      fuel: { fr: "Hybride", ar: "هجين" },
      transmission: { fr: "Automatique", ar: "أوتوماتيكي" },
      power: "140 ch",
      image:
        "/images/jogger.jpg",
      featured: true,
    },
    {
      key: "logan",
      brand: "Dacia",
      name: "Dacia Logan",
      category: { fr: "Berline", ar: "سيدان" },
      price: 134900,
      year: 2026,
      fuel: { fr: "Essence", ar: "بنزين" },
      transmission: { fr: "Manuelle", ar: "يدوي" },
      power: "90 ch",
      image:
        "/images/logan.jpg",
      featured: true,
    },
    {
      key: "clio",
      brand: "Renault",
      name: "Renault Clio",
      category: { fr: "Citadine premium", ar: "سيارة حضرية فاخرة" },
      price: 189900,
      year: 2026,
      fuel: { fr: "Hybride", ar: "هجين" },
      transmission: { fr: "Automatique", ar: "أوتوماتيكي" },
      power: "145 ch",
      image:
        "/images/clio.jpg",
      featured: true,
    },
    {
      key: "megane",
      brand: "Renault",
      name: "Renault Megane E-Tech",
      category: { fr: "SUV 100% électrique", ar: "سيارة كهربائية بالكامل" },
      price: 349900,
      year: 2026,
      fuel: { fr: "Électrique", ar: "كهربائي" },
      transmission: { fr: "Automatique", ar: "أوتوماتيكي" },
      power: "220 ch",
      image:
        "/images/megane.jpg",
      featured: true,
    },
  ],
  services: [
    { key: "new", icon: "car" },
    { key: "used", icon: "shield" },
    { key: "financing", icon: "wallet" },
    { key: "tradein", icon: "refresh" },
    { key: "maintenance", icon: "wrench" },
    { key: "insurance", icon: "shield" },
  ],
  heroImage:
    "/images/duster.jpg",
  url: "https://renaultdaciasafi.ma",
};

export type SiteConfig = typeof siteConfig;
